# Site settings
title: Li Yixuan
description: My Personal Site
keywords: NLP, CV, job
author: shinmanoko
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

deploy:
  type: git
  repo: https://github.com/LiYixuan727/LiYixuan727.github.io-myblog.git
  branch: master
  root: /myblog/