# Site settings
title: Li Yixuan
description: My Personal Site
keywords: NLP, CV, job
author: shinmanoko
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://shinmanoko.github.io/" # the base hostname & protocol for your site

deploy:
  type: git
  repo: https://github.com/shinmanoko/shinmanoko.github.io.git
  branch: master
  #root: /myblog/